pipeline {

  agent any
  environment {
    //adding a comment for the commit test
    DEPLOY_CREDS = credentials('c1fd2eb7-ea75-4f78-a811-e3f306f26a2f')
    MULE_VERSION = '4.4.0'
    BG = "Mulesoft"
    WORKER = "MICRO"
  }
  stages {
    stage('Build') {
      steps {
            bat 'mvn -B -U -e -V clean -DskipTests package'
      }
    }


     stage('Deploy Development') {
      environment {
        ENVIRONMENT = 'Sandbox'
        APP_NAME = 'sandbox-biofarma-poc-cicd'
      }
      steps {
            bat 'mvn -DskipTests deploy -DmuleDeploy '
      }
    }
  }

  tools {
    maven 'M3'
  }
}